// src/app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/app/components/Navbar';
import { ThemeProvider } from '@/context/theme-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
